### ISSUE TITLE
Machine Precision Frequency

### ISSUE THREAD

**Issue by znasipak** [BlackHolePerturbationToolkit/SpinWeightedSpheroidalHarmonics#1]
I'm not sure if you all are aware of this issue already, but SpinWeightedSpheroidalHarmonicsS seems to give an incorrect answer for larger values of |l-m| when you hand the function a spheroidicity at machine precision. Increasing the precision of the spheroidicity fixes this problem. Additionally, this problem only arises for the Leaver method. The eigenvalue method returns an accurate answer (up to a sign).

**Comment by barrywardell** [comment]
Thanks for the report. I have encountered the same problem myself. Right now, the straightforward solution is to work at higher precision as you say, but it would be much better to understand why the problem is happening and find a solution.

**Comment by nielsw2** [comment]
I guess if the matrix method is returning good values in the machine precision case we could just use that as the result and not pass it on as a seed to Leaver's method?

**Comment by barrywardell** [comment]
Commit 8ff1dd9 does as Niels suggested and uses the matrix method for machine precision calculations. It appears to work well in my test cases, but please let us know if you find a case where it causes problems.
