### ISSUE TITLE
Error in documentation for SpinWeightedSpheroidalHarmonicS for s=0

### ISSUE THREAD

**Issue by samdupton** [BlackHolePerturbationToolkit/SpinWeightedSpheroidalHarmonics#14]
In SpinWeightedSpheroidalHarmonicS.md, the line

"For s=0, SpinWeightedSpheroidalHarmonicS[0, l, m, \[Gamma], \[Theta], \[Phi]] is equivalent to Sqrt[(2 l + 1)/(4 \[Pi])] Sqrt[(l - m)!/(l + m)!] SpheroidalPS[l, m, I \[Gamma], Cos[\[Theta]]]."

should also state that the condition phi=0 is needed as well.

**Comment by barrywardell** [comment]
This has now been fixed, thanks for the report.
