### ISSUE TITLE
documentation for newbies

### ISSUE THREAD

**Issue by HelviWitek** [BlackHolePerturbationToolkit/SpinWeightedSpheroidalHarmonics#17]
Hi all,
this is great new toolkit! Congratulations.
I've been playing around a bit with the Spheroidal Harmonics, and looked  at the "SpinWeightedSpheroidalHarmonicSFunction" in the documentation notebook. Could you please add some documentation for this command, give an example and provide information about the options for "data" and "method"?
cheers
Helvi

**Comment by barrywardell** [comment]
Documentation has now been added for this function, and the documentation in general has also been updated and improved.
