### ISSUE TITLE
Consider getting DOSs for the packages

### ISSUE THREAD

**Issue by eschnett** [BlackHolePerturbationToolkit/SpinWeightedSpheroidalHarmonics#20]
Consider submitting the packages to [JOSS](https://joss.theoj.org), or creating releases on [Zenodo](https://zenodo.org).

**Comment by nielsw2** [comment]
Thanks for the suggestion. We recently created a [BHPToolkit Community on Zenodo](https://zenodo.org/communities/bhptoolkit/). When we formally release versions of each package we will deposit them on Zenodo as well. We expect to make the first releases this summer.

We'll also consider submitting to JOSS. At least one package has already done both of these (https://github.com/BlackHolePerturbationToolkit/qnm)

**Comment by barrywardell** [comment]
We have agreed that we will use GitHub's Zenodo link to create a DOI for future releases. See https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content for details on how to do this.
