### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by gabriel-andres-piovano** [BlackHolePerturbationToolkit/SpinWeightedSpheroidalHarmonics#21]
Hi,
I think I found a possible memory leak problem. I report here a minimal working example
```
In[1]:= $HistoryLength = 0;
<< SpinWeightedSpheroidalHarmonics`

In[3]:= MemoryInUse[]/1024.^2
Out[3]= 88.4061

In[4]:= SpinWeightedSpheroidalEigenvalue[-2,2,2,0.9 1/20`35];
SpinWeightedSpheroidalHarmonicS[-2,2,2,0.9 1/20`35,\[Pi]/2,0];

In[6]:= MemoryInUse[]/1024.^2
Out[6]= 88.4845

In[7]:= Table[
SpinWeightedSpheroidalEigenvalue[-2,2,2,0.9 1/20`35];
SpinWeightedSpheroidalHarmonicS[-2,2,2,0.9 1/20`35,\[Pi]/2,0];
,{i,100}];

In[8]:= MemoryInUse[]/1024.^2
Out[8]= 91.8491

In[9]:= Table[
SpinWeightedSpheroidalEigenvalue[-2,2,2,0.9 1/20`35];
SpinWeightedSpheroidalHarmonicS[-2,2,2,0.9 1/20`35,\[Pi]/2,0];
,{i,100}];

In[10]:= MemoryInUse[]/1024.^2
Out[10]= 95.213
```
I am using the latest version of SpinWeightedSpheroidalHarmonics and Mathematica 12.1. 
It seems odd to me that MemoryInUse increases so much in consecutive calls using `$HistoryLength=0` and semicolons. With `$HistoryLength=0`, Mathematica  should not store any previous calculations.
I noticed that if I input `?SpinWeightedSpheroidalHarmonics`Private`*`after calling the functions, I find many variables inside the "Private" context with name_variable$number. These seem to be local variables that are not garbage collected by some Modules inside the package. 
I attach an image
[SpinWeightedSpheroidalHarmonics-private.pdf](https://github.com/BlackHolePerturbationToolkit/SpinWeightedSpheroidalHarmonics/files/4671525/SpinWeightedSpheroidalHarmonics-private.pdf)
 of the content of `?SpinWeightedSpheroidalHarmonics`Private`* ` obtained by the following minimal code

```
<< SpinWeightedSpheroidalHarmonics`

SpinWeightedSpheroidalEigenvalue[-2,2,2,0.9 1/20`35];
SpinWeightedSpheroidalHarmonicS[-2,2,2,0.9 1/20`35,\[Pi]/2,0];

?SpinWeightedSpheroidalHarmonics`Private`*
```

**Comment by barrywardell** [comment]
Thanks for the report. I do not understand why this would be happening. For example, the symbol LHS is defined only inside a module in one place (see [here](https://github.com/BlackHolePerturbationToolkit/SpinWeightedSpheroidalHarmonics/blob/cb33143d83a1dc6d3c224392344ed434d0164074/Kernel/SpinWeightedSpheroidalHarmonics.m#L168)). This produces a Temporary symbol LHS$xxxx which should be garbage collected but is not. The same thing happens for a number of other local symbols.

As far as I can tell, this is not a bug in the SpinWeightedSpheroidalHarmonics package but is a behaviour of Mathematica. A brute-force solution would be to Remove all local symbols at the end of the function, but this seems to be counter to the whole point of Module.

**Comment by barrywardell** [comment]
This appears to be a known issue with Module, quoting from this [Stack Exchange answer](https://mathematica.stackexchange.com/a/569/316):

> One problem with local functions created by Module is that these symbols won't be automatically garbage-collected when Module finishes (if they have DownValues, SubValues or UpValues. OwnValues are fine), and so may lead to memory leaks. To avoid that, one can Clear these symbols inside Module before returning the result.result.

This suggests that we should clear all local functions before returning from the Module. This should be a fairly easy fix to do. We should also check if a similar issue affects other packages in the toolkit.

**Comment by barrywardell** [comment]
I have verified that commit bdd8285 fixes this and the reported memory leaks no longer occur.
