### ISSUE TITLE
Expose coefficients in the spheroidal to spherical expansion

### ISSUE THREAD

**Issue by nielsw2** [BlackHolePerturbationToolkit/SpinWeightedSpheroidalHarmonics#27]
Quite a few people have asked for the above. The code internally computes these coefficients (at least as many needed for the sum is correct to machine precision) but there is no API to access it.

Maybe we should add something like: `SpinWeightedSpheroidalToSphericalCoefficients[s,l,m,\[gamma]]`

**Comment by barrywardell** [comment]
We do expose these via the output form of a `SpinWeightedSpheroidalHarmonicSFunction`. We could add a Key in `SpinWeightedSpheroidalHarmonicSFunction` to extract this programmatically, so the usage would be something like:
```Mathematica
S = SpinWeightedSpheroidalHarmonicS[s, l, m, \[Gamma]];
S["ExpansionCoefficients"]
```
What should it return? Just the list of coefficients? Or also the range of l values?

**Comment by nielsw2** [comment]
I like the idea of a key, rather than a new function.

Depending on the method used the `SpinWeightedSpheroidalHarmonicSFunction` computes different coefficients (depending on Leaver vs SphericalExpansion for the Method option). So we would have to make the clear to the user.

The easier thing would be to return the coefficients as they are, but it would probably help the user to know the range of l values somehow.

**Comment by barrywardell** [comment]
We could add another key called BasisFunctions that would return a list of the basis functions.

**Comment by barrywardell** [comment]
The BasisFunctions idea was a bit messy as they have to be functions of theta and phi. It seemed simpler to just output the list of coefficients and include an index for each coefficient to indicate which basis function it corresponds to.

**Comment by barrywardell** [comment]
We agreed in an in-person meeting that the fix is suitable so the pull-request has now been merged.
