### ISSUE TITLE
Different result between Eigenvalue and Leaver method?

### ISSUE THREAD

**Issue by nielsw2** [BlackHolePerturbationToolkit/SpinWeightedSpheroidalHarmonics#3]
I get a different result for the Eigenvalue and Leaver method (it looks like the latter is wrong as it is complex when the result should be real. Leaver's method is used when gamma is given with extended precision.

S = SpinWeightedSpheroidalHarmonicS[1, 2, 2, 2.12`20];
S[\[Pi]/3., 0]

0. -0.0446104 i

S = SpinWeightedSpheroidalHarmonicS[1, 2, 2, 2.12];
S[\[Pi]/3., 0]

0.0535039

**Comment by jose-a-sa** [comment]
I had a similar problem when considering SpinWeightedSpheroidalHarmonicS[-1, 1, 1, 0] and SpinWeightedSpheroidalHarmonicS[-1, 1, 1, epsilon] for a very small epsilon

**Comment by nielsw2** [comment]
Hi Jose,

Can you give a concrete example where you were seeing a problem? I just tried using the latest version with Mathematica 11 and am seeing no problems for small epsilon for s=-1, l=1, m=1.

Cheers,
Niels

**Comment by jose-a-sa** [comment]
I think it was in an earlier version (bitbucket), now seems to work correctly. 

Cheers, José

**Comment by nielsw2** [comment]
Great!

**Comment by nielsw2** [comment]
Leaver's method does get the right answer once enough precision is used:

S = SpinWeightedSpheroidalHarmonicS[1, 2, 2, 2.12`50,  Method -> "Leaver"];
S[\[Pi]/3, 0]
0.0535038666531188483444223641572151165

Certainly we should detect a failure of the calculation when for real gamma (and phi=0) we have an imaginary result.

**Comment by barrywardell** [comment]
This appears to be the overall normalisation. You can check this be looking at the coefficients inside the SpinWeightedSpheriodalHarmonicSFunction stored in S. In the case reported by Niels, they are all wrong by a factor -0.8337780753*I, which is also the factor that the harmonic is wrong by.

**Comment by nielsw2** [comment]
There still seems to be an issue here related to precision, e.g.,

``SpinWeightedSpheroidalEigenvalue[2, 2, 2, 1.`40, Method -> "SphericalExpansion"]``
``SpinWeightedSpheroidalEigenvalue[2, 2, 2, 1.`40, Method -> "Leaver"]``
``1 - %/%%``

Returns 

``-6.45630962430790795816890111130352824186  ``
``-6.456309624307910336656043292148565446650  ``
``-3.68397316824130764703018*10^-16 ``

It looks like the SphericalExpansion method is only being evaluated to machine precision, despite having a higher precision input.

**Comment by barrywardell** [comment]
This is due to problems with the choice of nmax in the SphericalExpansion method, as discussed in #4 (it is not related to machine precision as far as I can see).
