### ISSUE TITLE
Indeterminate values

### ISSUE THREAD

**Issue by otoolec2** [BlackHolePerturbationToolkit/SpinWeightedSpheroidalHarmonics#6]
At certain values of l, m, s and theta, SpinWeightedSphericalHarmonicY returns 0^0, an indeterminate value.
Eg. l = 2, m = -2, s = -2, theta = pi

**Comment by barrywardell** [comment]
This should be straightforward to fix, by appropriately taking the limit theta->pi of

```Mathematica
Sin[\[Theta]/2]^(2 l - 2 r - s + m)] Cos[\[Theta]/2]^(2 r + s - m)
```

given the constraints on the integers l, r, s, and m. This could be added as another definition in certain cases.

We may also need to do similar for the theta->0 limit.
