### ISSUE TITLE
Harmonic calculation failing for Leaver's method

### ISSUE THREAD

**Issue by nielsw2** [BlackHolePerturbationToolkit/SpinWeightedSpheroidalHarmonics#8]
For some parts of the parameter space Leaver's method is returning 0. rather than the correct value. An example is:

`` With[{l = 7, m = 2, c = 20.`20, th = \[Pi]/4}, { ``
``  SpinWeightedSpheroidalHarmonicS[0, l, m, c, th, 0, Method -> "Leaver"],``
``  SpinWeightedSpheroidalHarmonicS[0, l, m, c, th, 0, Method -> "Eigenvalue"], ``
``  Sqrt[(2 l + 1)/(4 \[Pi])] Sqrt[(l - m)!/(l + m)!]SpheroidalPS[l, m, I c, Cos[th]]``
}]

which returns

`` {1.13134090*10^-11, -0.526441169303621589, -0.52644116930362158921} ``

**Comment by barrywardell** [comment]
The problem appears to be with the calculation of the normalisation. With the latest changes, this test case now produces lots of messages and returns Indeterminate instead of 0.

**Comment by barrywardell** [comment]
Commits 42bbce4 and b38af0d address this issue by producing an appropriate message indicating that insufficient precision has been used. The returned result also reflects this with a number with no significant digits.
