### ISSUE TITLE
Eigenvalue returned when |m| > l

### ISSUE THREAD

**Issue by halstonblim** [BlackHolePerturbationToolkit/SpinWeightedSpheroidalHarmonics#9]
Evaluating s = -2, l = 2, m = 3, gamma = 0 

In[]:= SpinWeightedSpheroidalEigenvalue[-2, 2, 3, 0]

returns

Out[]= 4

should return a flag instead?

**Comment by barrywardell** [comment]
I'm not sure what the right thing to do is here. Mathematica's SpheroidalEigenvalue (for s=0) returns l(l+1) like we currently do, although that's not necessarily a reason to do the same.

**Comment by barrywardell** [comment]
The package now produces an error message when given unphysical parameters. We may wish to consider allowing unphysical parameters in the future, but the code doesn't currently work in that case due to the line `nInv = l-Max[Abs[m],Abs[s]]`.
